/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ParametresRouteImport } from './routes/parametres'
import { Route as JoueursRouteImport } from './routes/joueurs'
import { Route as ConcoursRouteImport } from './routes/concours'
import { Route as IndexRouteImport } from './routes/index'
import { Route as JoueursIndexRouteImport } from './routes/joueurs.index'
import { Route as ConcoursIndexRouteImport } from './routes/concours.index'
import { Route as JoueursNouveauRouteImport } from './routes/joueurs.nouveau'
import { Route as ConcoursNouveauRouteImport } from './routes/concours.nouveau'
import { Route as ConcoursArchivesRouteImport } from './routes/concours.archives'
import { Route as ConcoursConcoursIdRouteImport } from './routes/concours.$concoursId'
import { Route as ConcoursConcoursIdHistoriqueRouteImport } from './routes/concours.$concoursId.historique'

const ParametresRoute = ParametresRouteImport.update({
  id: '/parametres',
  path: '/parametres',
  getParentRoute: () => rootRouteImport,
} as any)
const JoueursRoute = JoueursRouteImport.update({
  id: '/joueurs',
  path: '/joueurs',
  getParentRoute: () => rootRouteImport,
} as any)
const ConcoursRoute = ConcoursRouteImport.update({
  id: '/concours',
  path: '/concours',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const JoueursIndexRoute = JoueursIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => JoueursRoute,
} as any)
const ConcoursIndexRoute = ConcoursIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ConcoursRoute,
} as any)
const JoueursNouveauRoute = JoueursNouveauRouteImport.update({
  id: '/nouveau',
  path: '/nouveau',
  getParentRoute: () => JoueursRoute,
} as any)
const ConcoursNouveauRoute = ConcoursNouveauRouteImport.update({
  id: '/nouveau',
  path: '/nouveau',
  getParentRoute: () => ConcoursRoute,
} as any)
const ConcoursArchivesRoute = ConcoursArchivesRouteImport.update({
  id: '/archives',
  path: '/archives',
  getParentRoute: () => ConcoursRoute,
} as any)
const ConcoursConcoursIdRoute = ConcoursConcoursIdRouteImport.update({
  id: '/$concoursId',
  path: '/$concoursId',
  getParentRoute: () => ConcoursRoute,
} as any)
const ConcoursConcoursIdHistoriqueRoute =
  ConcoursConcoursIdHistoriqueRouteImport.update({
    id: '/historique',
    path: '/historique',
    getParentRoute: () => ConcoursConcoursIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/concours': typeof ConcoursRouteWithChildren
  '/joueurs': typeof JoueursRouteWithChildren
  '/parametres': typeof ParametresRoute
  '/concours/$concoursId': typeof ConcoursConcoursIdRouteWithChildren
  '/concours/archives': typeof ConcoursArchivesRoute
  '/concours/nouveau': typeof ConcoursNouveauRoute
  '/joueurs/nouveau': typeof JoueursNouveauRoute
  '/concours/': typeof ConcoursIndexRoute
  '/joueurs/': typeof JoueursIndexRoute
  '/concours/$concoursId/historique': typeof ConcoursConcoursIdHistoriqueRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/parametres': typeof ParametresRoute
  '/concours/$concoursId': typeof ConcoursConcoursIdRouteWithChildren
  '/concours/archives': typeof ConcoursArchivesRoute
  '/concours/nouveau': typeof ConcoursNouveauRoute
  '/joueurs/nouveau': typeof JoueursNouveauRoute
  '/concours': typeof ConcoursIndexRoute
  '/joueurs': typeof JoueursIndexRoute
  '/concours/$concoursId/historique': typeof ConcoursConcoursIdHistoriqueRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/concours': typeof ConcoursRouteWithChildren
  '/joueurs': typeof JoueursRouteWithChildren
  '/parametres': typeof ParametresRoute
  '/concours/$concoursId': typeof ConcoursConcoursIdRouteWithChildren
  '/concours/archives': typeof ConcoursArchivesRoute
  '/concours/nouveau': typeof ConcoursNouveauRoute
  '/joueurs/nouveau': typeof JoueursNouveauRoute
  '/concours/': typeof ConcoursIndexRoute
  '/joueurs/': typeof JoueursIndexRoute
  '/concours/$concoursId/historique': typeof ConcoursConcoursIdHistoriqueRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/concours'
    | '/joueurs'
    | '/parametres'
    | '/concours/$concoursId'
    | '/concours/archives'
    | '/concours/nouveau'
    | '/joueurs/nouveau'
    | '/concours/'
    | '/joueurs/'
    | '/concours/$concoursId/historique'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/parametres'
    | '/concours/$concoursId'
    | '/concours/archives'
    | '/concours/nouveau'
    | '/joueurs/nouveau'
    | '/concours'
    | '/joueurs'
    | '/concours/$concoursId/historique'
  id:
    | '__root__'
    | '/'
    | '/concours'
    | '/joueurs'
    | '/parametres'
    | '/concours/$concoursId'
    | '/concours/archives'
    | '/concours/nouveau'
    | '/joueurs/nouveau'
    | '/concours/'
    | '/joueurs/'
    | '/concours/$concoursId/historique'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ConcoursRoute: typeof ConcoursRouteWithChildren
  JoueursRoute: typeof JoueursRouteWithChildren
  ParametresRoute: typeof ParametresRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/parametres': {
      id: '/parametres'
      path: '/parametres'
      fullPath: '/parametres'
      preLoaderRoute: typeof ParametresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/joueurs': {
      id: '/joueurs'
      path: '/joueurs'
      fullPath: '/joueurs'
      preLoaderRoute: typeof JoueursRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/concours': {
      id: '/concours'
      path: '/concours'
      fullPath: '/concours'
      preLoaderRoute: typeof ConcoursRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/joueurs/': {
      id: '/joueurs/'
      path: '/'
      fullPath: '/joueurs/'
      preLoaderRoute: typeof JoueursIndexRouteImport
      parentRoute: typeof JoueursRoute
    }
    '/concours/': {
      id: '/concours/'
      path: '/'
      fullPath: '/concours/'
      preLoaderRoute: typeof ConcoursIndexRouteImport
      parentRoute: typeof ConcoursRoute
    }
    '/joueurs/nouveau': {
      id: '/joueurs/nouveau'
      path: '/nouveau'
      fullPath: '/joueurs/nouveau'
      preLoaderRoute: typeof JoueursNouveauRouteImport
      parentRoute: typeof JoueursRoute
    }
    '/concours/nouveau': {
      id: '/concours/nouveau'
      path: '/nouveau'
      fullPath: '/concours/nouveau'
      preLoaderRoute: typeof ConcoursNouveauRouteImport
      parentRoute: typeof ConcoursRoute
    }
    '/concours/archives': {
      id: '/concours/archives'
      path: '/archives'
      fullPath: '/concours/archives'
      preLoaderRoute: typeof ConcoursArchivesRouteImport
      parentRoute: typeof ConcoursRoute
    }
    '/concours/$concoursId': {
      id: '/concours/$concoursId'
      path: '/$concoursId'
      fullPath: '/concours/$concoursId'
      preLoaderRoute: typeof ConcoursConcoursIdRouteImport
      parentRoute: typeof ConcoursRoute
    }
    '/concours/$concoursId/historique': {
      id: '/concours/$concoursId/historique'
      path: '/historique'
      fullPath: '/concours/$concoursId/historique'
      preLoaderRoute: typeof ConcoursConcoursIdHistoriqueRouteImport
      parentRoute: typeof ConcoursConcoursIdRoute
    }
  }
}

interface ConcoursConcoursIdRouteChildren {
  ConcoursConcoursIdHistoriqueRoute: typeof ConcoursConcoursIdHistoriqueRoute
}

const ConcoursConcoursIdRouteChildren: ConcoursConcoursIdRouteChildren = {
  ConcoursConcoursIdHistoriqueRoute: ConcoursConcoursIdHistoriqueRoute,
}

const ConcoursConcoursIdRouteWithChildren =
  ConcoursConcoursIdRoute._addFileChildren(ConcoursConcoursIdRouteChildren)

interface ConcoursRouteChildren {
  ConcoursConcoursIdRoute: typeof ConcoursConcoursIdRouteWithChildren
  ConcoursArchivesRoute: typeof ConcoursArchivesRoute
  ConcoursNouveauRoute: typeof ConcoursNouveauRoute
  ConcoursIndexRoute: typeof ConcoursIndexRoute
}

const ConcoursRouteChildren: ConcoursRouteChildren = {
  ConcoursConcoursIdRoute: ConcoursConcoursIdRouteWithChildren,
  ConcoursArchivesRoute: ConcoursArchivesRoute,
  ConcoursNouveauRoute: ConcoursNouveauRoute,
  ConcoursIndexRoute: ConcoursIndexRoute,
}

const ConcoursRouteWithChildren = ConcoursRoute._addFileChildren(
  ConcoursRouteChildren,
)

interface JoueursRouteChildren {
  JoueursNouveauRoute: typeof JoueursNouveauRoute
  JoueursIndexRoute: typeof JoueursIndexRoute
}

const JoueursRouteChildren: JoueursRouteChildren = {
  JoueursNouveauRoute: JoueursNouveauRoute,
  JoueursIndexRoute: JoueursIndexRoute,
}

const JoueursRouteWithChildren =
  JoueursRoute._addFileChildren(JoueursRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ConcoursRoute: ConcoursRouteWithChildren,
  JoueursRoute: JoueursRouteWithChildren,
  ParametresRoute: ParametresRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
